image: java:8-jdk

variables:
  GIT_STRATEGY: clone

before_script:
  - export GRADLE_USER_HOME='pwd'/.gradle
  - chmod +x ./gradlew

cache:
  paths:
    - .gradle/wrapper --gradle-version=6.6.1 --distribution-type=bin
    - .gradle/caches

stages:
  - build
  - test
  - deploy

build:
  image: gradle:alpine
  stage: build
  script: 
    - ./gradlew assemble
  tags:
    - ugrad

test:
  stage: test
  script:
    - ./gradlew check
  tags:
    - ugrad

