image: java:8-jdk

variables:
  GIT_STRATEGY: clone

before_script:
  - export GRADLE_USER_HOME='pwd'/.gradle
  - chmod +x ./gradlew

cache:
  paths:
    - .gradle/wrapper --gradle-version=6.6.1 --distribution-type=bin
    - .gradle/caches

stages:
  - build
  - test
  - deploy

build:
  image: gradle:alpine
  stage: build
  script: 
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
  tags:
    - ugrad

test:
  stage: test
  script:
    - ./gradlew check
  tags:
    - ugrad

deploy:
  stage: deploy
  before_script:
    - mkdir -p ~/.ssh
    - echo "$DEPLOY_SSH_KEY" | tr -d '\r' > ~./ssh/id_rsa
    - chmod 700 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H 'gitlab.com' >> ~/.ssh/known_hosts
  script:
    - chmod og-rwx ${DEPLOY_SSH_KEY}
    - zip -r ${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}.zip . -i ${DEPLOY_DIR}
    - scp -r "${DEPLOY_SSH_KEY}" /build/libs/*.jar "${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}/${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}.zip"
  tags:
    - ugrad